# Change these first
owner: madtownchris # Your GitHub organization or username, where this repository lives
repo: pidge-uptime # The name of this repository

sites:
  - name: Pidge
    url: https://www.pidgepost.com
  - name: Pidge Test
    url: https://pidgepostdev.wpengine.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /pidge-uptime
  logoUrl: https://pidgepost.com/wp-content/uploads/2021/06/Pidge-Post-Logo-Set_Pidge-Post-icon-1200x1200-circle-1-e1624061645186.png
  name: Pidge Uptime
  introTitle: "Pidgepost status page poweed by Upptime"
  introMessage: Pidgepost.com status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
